In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

In [2]:
training_set = pd.read_csv("Google_Stock_PRice_Train.csv") 

In [3]:
training_set.head() 

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [5]:
training_set.tail()  

Date    Open    High     Low   Close     Volume
1253  12/23/2016  790.90  792.74  787.28  789.91    623,400
1254  12/27/2016  790.68  797.86  787.66  791.55    789,100
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

In [6]:
training_set = training_set.iloc[:, 1:2].values 

In [7]:
training_set 

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [8]:
def split_sequence(sequence, n_steps):
    x, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y) 

In [10]:
from numpy import array 

In [11]:
n_steps = 3
x, y = split_sequence(training_set, n_steps)
for i in range(len(x)):
    print(x[i], y[i]) 

[[325.25]
 [331.27]
 [329.83]] [328.34]
[[331.27]
 [329.83]
 [328.34]] [322.04]
[[329.83]
 [328.34]
 [322.04]] [313.7]
[[328.34]
 [322.04]
 [313.7 ]] [310.59]
[[322.04]
 [313.7 ]
 [310.59]] [314.43]
[[313.7 ]
 [310.59]
 [314.43]] [311.96]
[[310.59]
 [314.43]
 [311.96]] [314.81]
[[314.43]
 [311.96]
 [314.81]] [312.14]
[[311.96]
 [314.81]
 [312.14]] [319.3]
[[314.81]
 [312.14]
 [319.3 ]] [294.16]
[[312.14]
 [319.3 ]
 [294.16]] [291.91]
[[319.3 ]
 [294.16]
 [291.91]] [292.07]
[[294.16]
 [291.91]
 [292.07]] [287.68]
[[291.91]
 [292.07]
 [287.68]] [284.92]
[[292.07]
 [287.68]
 [284.92]] [284.32]
[[287.68]
 [284.92]
 [284.32]] [287.95]
[[284.92]
 [284.32]
 [287.95]] [290.41]
[[284.32]
 [287.95]
 [290.41]] [291.38]
[[287.95]
 [290.41]
 [291.38]] [291.34]
[[290.41]
 [291.38]
 [291.34]] [294.23]
[[291.38]
 [291.34]
 [294.23]] [296.39]
[[291.34]
 [294.23]
 [296.39]] [302.44]
[[294.23]
 [296.39]
 [302.44]] [303.18]
[[296.39]
 [302.44]
 [303.18]] [304.87]
[[302.44]
 [303.18]
 [304.87]] [302.81]
[[

[[333.25]
 [333.73]
 [331.98]] [328.85]
[[333.73]
 [331.98]
 [328.85]] [332.76]
[[331.98]
 [328.85]
 [332.76]] [342.61]
[[328.85]
 [332.76]
 [342.61]] [344.36]
[[332.76]
 [342.61]
 [344.36]] [349.81]
[[342.61]
 [344.36]
 [349.81]] [346.2]
[[344.36]
 [349.81]
 [346.2 ]] [344.78]
[[349.81]
 [346.2 ]
 [344.78]] [342.51]
[[346.2 ]
 [344.78]
 [342.51]] [346.2]
[[344.78]
 [342.51]
 [346.2 ]] [341.42]
[[342.51]
 [346.2 ]
 [341.42]] [343.71]
[[346.2 ]
 [341.42]
 [343.71]] [348.31]
[[341.42]
 [343.71]
 [348.31]] [356.62]
[[343.71]
 [348.31]
 [356.62]] [348.28]
[[348.31]
 [356.62]
 [348.28]] [351.43]
[[356.62]
 [348.28]
 [351.43]] [356.96]
[[348.28]
 [351.43]
 [356.96]] [359.01]
[[351.43]
 [356.96]
 [359.01]] [360.28]
[[356.96]
 [359.01]
 [360.28]] [355.65]
[[359.01]
 [360.28]
 [355.65]] [355.92]
[[360.28]
 [355.65]
 [355.92]] [352.71]
[[355.65]
 [355.92]
 [352.71]] [352.25]
[[355.92]
 [352.71]
 [352.25]] [349.53]
[[352.71]
 [352.25]
 [349.53]] [348.69]
[[352.25]
 [349.53]
 [348.69]] [358.37]
[[

 [431.4 ]] [431.71]
[[430.31]
 [431.4 ]
 [431.71]] [436.24]
[[431.4 ]
 [431.71]
 [436.24]] [441.28]
[[431.71]
 [436.24]
 [441.28]] [444.83]
[[436.24]
 [441.28]
 [444.83]] [486.47]
[[441.28]
 [444.83]
 [486.47]] [503.84]
[[444.83]
 [486.47]
 [503.84]] [500.62]
[[486.47]
 [503.84]
 [500.62]] [498.63]
[[503.84]
 [500.62]
 [498.63]] [514.01]
[[500.62]
 [498.63]
 [514.01]] [512.49]
[[498.63]
 [514.01]
 [512.49]] [505.7]
[[514.01]
 [512.49]
 [505.7 ]] [507.65]
[[512.49]
 [505.7 ]
 [507.65]] [516.78]
[[505.7 ]
 [507.65]
 [516.78]] [512.54]
[[507.65]
 [516.78]
 [512.54]] [513.97]
[[516.78]
 [512.54]
 [513.97]] [513.82]
[[512.54]
 [513.97]
 [513.82]] [508.27]
[[513.97]
 [513.82]
 [508.27]] [510.89]
[[513.82]
 [508.27]
 [510.89]] [509.4]
[[508.27]
 [510.89]
 [509.4 ]] [502.49]
[[510.89]
 [509.4 ]
 [502.49]] [502.87]
[[509.4 ]
 [502.49]
 [502.87]] [501.97]
[[502.49]
 [502.87]
 [501.97]] [501.5]
[[502.87]
 [501.97]
 [501.5 ]] [515.03]
[[501.97]
 [501.5 ]
 [515.03]] [515.5]
[[501.5 ]
 [515.03]
 [51

[[548.49]
 [547.45]
 [557.82]] [553.98]
[[547.45]
 [557.82]
 [553.98]] [551.49]
[[557.82]
 [553.98]
 [551.49]] [555.28]
[[553.98]
 [551.49]
 [555.28]] [544.01]
[[551.49]
 [555.28]
 [544.01]] [544.71]
[[555.28]
 [544.01]
 [544.71]] [539.98]
[[544.01]
 [544.71]
 [539.98]] [546.99]
[[544.71]
 [539.98]
 [546.99]] [548.88]
[[539.98]
 [546.99]
 [548.88]] [548.29]
[[546.99]
 [548.88]
 [548.29]] [545.18]
[[548.88]
 [548.29]
 [545.18]] [542.09]
[[548.29]
 [545.18]
 [542.09]] [536.03]
[[545.18]
 [542.09]
 [536.03]] [533.54]
[[542.09]
 [536.03]
 [533.54]] [529.8]
[[536.03]
 [533.54]
 [529.8 ]] [540.13]
[[533.54]
 [529.8 ]
 [540.13]] [536.18]
[[529.8 ]
 [540.13]
 [536.18]] [537.52]
[[540.13]
 [536.18]
 [537.52]] [539.4]
[[536.18]
 [537.52]
 [539.4 ]] [539.14]
[[537.52]
 [539.4 ]
 [539.14]] [537.42]
[[539.4 ]
 [539.14]
 [537.42]] [532.05]
[[539.14]
 [537.42]
 [532.05]] [529.98]
[[537.42]
 [532.05]
 [529.98]] [529.71]
[[532.05]
 [529.98]
 [529.71]] [529.55]
[[529.98]
 [529.71]
 [529.55]] [525.69]
[[

 [627.  ]] [622.05]
[[634.4 ]
 [627.  ]
 [622.05]] [616.64]
[[627.  ]
 [622.05]
 [616.64]] [629.77]
[[622.05]
 [616.64]
 [629.77]] [610.34]
[[616.64]
 [629.77]
 [610.34]] [597.28]
[[629.77]
 [610.34]
 [597.28]] [603.28]
[[610.34]
 [597.28]
 [603.28]] [608.37]
[[597.28]
 [603.28]
 [608.37]] [607.2]
[[603.28]
 [608.37]
 [607.2 ]] [632.]
[[608.37]
 [607.2 ]
 [632.  ]] [638.84]
[[607.2 ]
 [632.  ]
 [638.84]] [649.24]
[[632.  ]
 [638.84]
 [649.24]] [641.36]
[[638.84]
 [649.24]
 [641.36]] [640.]
[[649.24]
 [641.36]
 [640.  ]] [642.09]
[[641.36]
 [640.  ]
 [642.09]] [643.15]
[[640.  ]
 [642.09]
 [643.15]] [653.21]
[[642.09]
 [643.15]
 [653.21]] [654.66]
[[643.15]
 [653.21]
 [654.66]] [664.11]
[[653.21]
 [654.66]
 [664.11]] [661.18]
[[654.66]
 [664.11]
 [661.18]] [664.04]
[[664.11]
 [661.18]
 [664.04]] [654.15]
[[661.18]
 [664.04]
 [654.15]] [646.7]
[[664.04]
 [654.15]
 [646.7 ]] [727.5]
[[654.15]
 [646.7 ]
 [727.5 ]] [701.55]
[[646.7 ]
 [727.5 ]
 [701.55]] [707.38]
[[727.5 ]
 [701.55]
 [707.3

 [773.78]] [782.]
[[772.22]
 [773.78]
 [782.  ]] [781.1]
[[773.78]
 [782.  ]
 [781.1 ]] [783.75]
[[782.  ]
 [781.1 ]
 [783.75]] [785.]
[[781.1 ]
 [783.75]
 [785.  ]] [781.5]
[[783.75]
 [785.  ]
 [781.5 ]] [783.75]
[[785.  ]
 [781.5 ]
 [783.75]] [780.3]
[[781.5 ]
 [783.75]
 [780.3 ]] [777.32]
[[783.75]
 [780.3 ]
 [777.32]] [780.01]
[[780.3 ]
 [777.32]
 [780.01]] [775.]
[[777.32]
 [780.01]
 [775.  ]] [773.27]
[[780.01]
 [775.  ]
 [773.27]] [775.48]
[[775.  ]
 [773.27]
 [775.48]] [770.58]
[[773.27]
 [775.48]
 [770.58]] [767.]
[[775.48]
 [770.58]
 [767.  ]] [769.]
[[770.58]
 [767.  ]
 [769.  ]] [768.74]
[[767.  ]
 [769.  ]
 [768.74]] [769.33]
[[769.  ]
 [768.74]
 [769.33]] [767.01]
[[768.74]
 [769.33]
 [767.01]] [769.25]
[[769.33]
 [767.01]
 [769.25]] [773.01]
[[767.01]
 [769.25]
 [773.01]] [773.45]
[[769.25]
 [773.01]
 [773.45]] [780.]
[[773.01]
 [773.45]
 [780.  ]] [778.59]
[[773.45]
 [780.  ]
 [778.59]] [770.1]
[[780.  ]
 [778.59]
 [770.1 ]] [755.13]
[[778.59]
 [770.1 ]
 [755.13]] [764.

In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D 

In [19]:
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))

In [20]:
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse') 

Instructions for updating:
Colocations handled automatically by placer.


In [23]:
model.fit(x, y, epochs = 200, verbose = 0) 

In [24]:
x


array([[[325.25],
        [331.27],
        [329.83]],

       [[331.27],
        [329.83],
        [328.34]],

       [[329.83],
        [328.34],
        [322.04]],

       ...,

       [[792.36],
        [790.9 ],
        [790.68]],

       [[790.9 ],
        [790.68],
        [793.7 ]],

       [[790.68],
        [793.7 ],
        [783.33]]])

In [44]:
x_input = array([837.81, 834.71, 814.66])

In [45]:
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat) 

[[826.8316]]
